spring.application.name=socialMedia


# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_URL:jdbc:h2:mem:socialmedia;DB_CLOSE_DELAY=-1;MODE=MYSQL}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.h2.Driver}

spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.address=0.0.0.0
server.port=${PORT:8080}


jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

logging.level.org.springframework.security=INFO

app.frontend.url=${FRONTEND_URLS:${FRONTEND_URL:http://localhost:5173}}